CREATE TABLE CUSTOMER (
    CUSTOMER_ID BIGINT NOT NULL,
    NAME VARCHAR(120) NOT NULL,
    DOCUMENT VARCHAR(20) NOT NULL,
    PRIMARY KEY (CUSTOMER_ID)
);

CREATE TABLE ACCOUNT (
    ACCOUNT_ID BIGINT NOT NULL,
    CUSTOMER_ID BIGINT NOT NULL,
    BALANCE DECIMAL(15,2) NOT NULL DEFAULT 0,
    STATUS VARCHAR(10) NOT NULL DEFAULT 'ACTIVE',
    PRIMARY KEY (ACCOUNT_ID),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)
);

CREATE TABLE BANK_TRANSACTION (
    TRANSACTION_ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
    ACCOUNT_ID BIGINT NOT NULL,
    TRANSACTION_TYPE VARCHAR(20) NOT NULL,
    AMOUNT DECIMAL(15,2) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP,
    PRIMARY KEY (TRANSACTION_ID),
    FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ACCOUNT_ID)
);
