SELECT A.ACCOUNT_ID, C.NAME, A.BALANCE, A.STATUS
FROM ACCOUNT A JOIN CUSTOMER C ON C.CUSTOMER_ID = A.CUSTOMER_ID
WHERE A.ACCOUNT_ID = 1000000001;

SELECT TRANSACTION_ID, TRANSACTION_TYPE, AMOUNT, CREATED_AT
FROM BANK_TRANSACTION
WHERE ACCOUNT_ID = 1000000001
ORDER BY CREATED_AT DESC;
